apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awx-projects-pvc
  namespace: awx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-readynas
  resources:
    requests:
      storage: 8Gi
